
export const UPDATE_INPUT_PAGEBAR = "UPDATE_INPUT_PAGEBAR" ;
export const QUERYLIST_FOR_PAGE = "QUERYLIST_FOR_PAGE" ;
export const UPDATE_SIMPLE_STATE= "UPDATE_SIMPLE_STATE" ;//简单更新state数据
export const ORDER_LISTDATA = "ORDER_LISTDATA" ; //orderListData
export const UPDATE_TABLETITLE_ORDER = "UPDATE_TABLETITLE_ORDER" ;
export const CLEAR_TABLETITLE_ORDERINFO = "CLEAR_TABLETITLE_ORDERINFO" ;
export const defaultOrderFlag = true ;